### ISSUE TITLE
How to import

### ISSUE THREAD

**Issue by ben4d85** [DamianoMagrini/react-stack-navigator#10]
How can I import this?

```
import { StackNavigator } from 'react-stack-navigator';
```

leads to the following error when trying to use it:

```
ERROR in ./src/App.js 42:35-49

export 'StackNavigator' (imported as 'StackNavigator') was not found in 'react-stack-navigator' (module has no exports)


ERROR in ./node_modules/react-stack-navigator/lib/index.js 1:0-33

Module not found: Error: Can't resolve './StackNavigator' in '/Users/.../node_modules/react-stack-navigator/lib'
Did you mean 'StackNavigator.js'?
BREAKING CHANGE: The request './StackNavigator' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.


ERROR in ./node_modules/react-stack-navigator/lib/index.js 2:0-40

Module not found: Error: Can't resolve './StackNavigatorContext' in '/Users/.../node_modules/react-stack-navigator/lib'
Did you mean 'StackNavigatorContext.js'?
BREAKING CHANGE: The request './StackNavigatorContext' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.


ERROR in ./node_modules/react-stack-navigator/lib/index.js 3:0-36

Module not found: Error: Can't resolve './useStackNavigator' in '/Users/.../node_modules/react-stack-navigator/lib'
Did you mean 'useStackNavigator.js'?
BREAKING CHANGE: The request './useStackNavigator' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by DamianoMagrini** [comment]
Hmm… what compiler/bundler are you using? It looks like it requires you to specify the file extensions when importing files, which the library currently doesn't do

**Comment by ben4d85** [comment]
Thank you for the quick response!

This happens with a fresh [Create React App](https://github.com/facebook/create-react-app) project (uses Webpack).

Can this be fixed?

**Comment by DamianoMagrini** [comment]
Alright, should be fixed in 0.4.2. Let me know if it works now!

**Comment by ben4d85** [comment]
Yes, I can run it now! Thank you!

I did notice that when I push something, e.g. `<button onClick={() => push(<MyNewScene />)}>Change Scene</button>`, I get the following warning in the console:

```
react_devtools_backend.js:4045 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:36058:30)
    at CSSTransition (http://localhost:3000/static/js/bundle.js:35609:35)
    at div
    at TransitionGroup (http://localhost:3000/static/js/bundle.js:36628:30)
    at StackNavigator (http://localhost:3000/static/js/bundle.js:45010:5)
    at div
    at App
```

**Comment by DamianoMagrini** [comment]
Hmm, that looks like an issue with React Transition Group, I'm afraid I can't do much about it

As for the main issue, I'm glad it's solved now! I'll go ahead and close it then
